### ISSUE TITLE
GPU usage 0% at M2 Max MacBook Pro

### ISSUE THREAD

**Issue by kposy** [jankais3r/LLaMA_MPS#2]
Thank you so much for providing this repository! I tested it on my M2 Max Pro using the 13B model, the loading process took more than 120 seconds without utilizing the MPS backend.  Furthermore, the model generates only around one word per three minutes, which seems to be unusually slow.

**Comment by jankais3r** [comment]
Hi, I don't understand how such thing could happen - the code is written to use mps and has no fallback to CPU in case mps isn't available for whatever reason…

To help you figure out what's going on, please repeat all steps from the readme, and reply here with the complete output from your terminal.

**Comment by kposy** [comment]
Thanks for the reply! The 7B model works perfect, guess it's the swap problem.(My RAM is only 32G)
