### ISSUE TITLE
The magnet link of the model resource seem to be unusable

### ISSUE THREAD

**Issue by tsonubin** [jankais3r/LLaMA_MPS#9]
I know this might be improper to ask here, but how can I get access to the model weight more easily?

Tried to request access by haven't receive an email yet.

Thanks.

**Comment by tsonubin** [comment]
<img width="1338" alt="CleanShot 2023-03-19 at 21 56 57@2x" src="https://user-images.githubusercontent.com/10642396/226180921-f860de08-02cf-4963-ac8b-a00c588a7e2e.png">

**Comment by jankais3r** [comment]
The magnet link should work just fine, but if you are having troubles, check [llama-dl](https://github.com/shawwn/llama-dl)

**Comment by ValZapod** [comment]
Now here after take down: https://gist.github.com/shawwn/3ae33be3507ccd766c4ad76d64ce2587

Still works.
